#!/bin/bash
pintos="$(dirname $0)"
pintos="$(dirname $pintos)"

echo $pintos

dockerid=$pintos/.container-id

if [ ! -f "$dockerid" ]; then
    docker create -t -i -v $PINTOS_HOME:/root/pintos \
    -v $PINTOS_HOME/pintos-docker:/root/host -p 1234:1234 --cidfile $dockerid gbenm/pintos:latest
fi

dockerid=`cat $dockerid`

if [[ -n "$(docker container list --no-trunc -q | grep $dockerid)" ]];
then
    docker exec -it $dockerid bash
else
    docker start -i $dockerid
fi

